/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"


void
square_proc_1(char *host, char *data)
{
	CLIENT *clnt;
	int  *result_1;
	square  sqr_1_arg;
	sqr_1_arg.a = atoi(data);
#ifndef	DEBUG
	clnt = clnt_create (host, SQUARE_PROC, SQUARE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sqr_1(&sqr_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%d\n",result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	square_proc_1 (host,argv[2]);
exit (0);
}
