/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "square.h"

int *
sqr_1_svc(square *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
 	result = argp->a * argp->a;
	return &result;
}
