/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum {
	int data[5];
	int size;
};
typedef struct sum sum;

#define SUM_PROG 0x3012225
#define SUM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumOfArray 1
extern  int * sumofarray_1(sum *, CLIENT *);
extern  int * sumofarray_1_svc(sum *, struct svc_req *);
extern int sum_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumOfArray 1
extern  int * sumofarray_1();
extern  int * sumofarray_1_svc();
extern int sum_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum (XDR *, sum*);

#else /* K&R C */
extern bool_t xdr_sum ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
